# Generated by Django 5.2.7 on 2025-10-31 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchvehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Черновик', 'Draft'), ('Удален', 'Deleted'), ('В расчете', 'Formed'), ('Расчет завершен', 'Completed'), ('Ошибка в расчете', 'Rejected')], default='Черновик', max_length=25)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('location', models.IntegerField(blank=True, null=True, verbose_name='Широта космодрома')),
                ('port_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порт')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='Результат вычислений')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='launchvehicle.launchvehicle', verbose_name='Ракета')),
                ('payload_calculation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='launchvehicle.payloadcalculation', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
