# Generated by Django 5.2.7 on 2025-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('gto_playload', models.IntegerField(verbose_name='Полезная нагрузка (кг)')),
                ('imagerocket', models.ImageField(blank=True, null=True, upload_to='rockets/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Ракета-носитель',
                'verbose_name_plural': 'Ракеты-носители',
            },
        ),
    ]
