# Generated by Django 5.2.6 on 2026-01-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchvehicle', '0004_twofactorauth_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
